### ISSUE TITLE
CI should push new tagged releases to pip

### ISSUE THREAD

**Issue by sterrettJD** [lozuponelab/KEGG_parser#14]
Hey @kthurimella , can we set up continuous integration to send new tagged releases to PyPI? 

Currently, `KEGG_parser` is functioning, but when people install AMON, it is still pulling `KEGG_parser` from pip, which isn't updated. 

It shouldn't be too hard to set this up - I would follow the directions explained [here](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/). I just need a PyPI API token for the repo from you, or if you could add me to the PyPI repo I could do that. Could you generate the token following [these steps](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/) and add it to the GitHub repo's secrets using the steps listed [here](https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/)?

Thanks!

**Comment by kthurimella** [comment]
Hey John, please see my email with the transfer of account information.

**Comment by sterrettJD** [comment]
@kthurimella CI now pushes new releases to pip! And the current version is available on pip.
